### ISSUE TITLE
Some broken links

### ISSUE THREAD

**Issue by raphaelsaavedra** [NREL-SIIP/SIIPExamples.jl#10]
There are some links in the notebooks leading to https://github.com/grid-mod/rts-gmlc that are broken (possibly an old URL). I believe they should lead to https://github.com/NREL-SIIP/PowerSystemsTestData/tree/master/RTS_GMLC?

**Comment by claytonpbarrows** [comment]
Thanks @raphaelsaavedra, in this case, the link should point to https://github.com/gridmod/rts-gmlc
I'll make the updates

**Comment by claytonpbarrows** [comment]
04cd64ea360e9b3328d0fee7748ff109d4c7cc61 closes
