### ISSUE TITLE
proper components not removed when building modified_RTS_GMLC_DA_sys in script/3_PowerSimulations_examples/01_operations_problems.jl 

### ISSUE THREAD

**Issue by ninamvincent** [NREL-SIIP/SIIPExamples.jl#26]
I'm occasionally getting errors with initial conditions when I expand on this example to include more days.

When I load in:
`sys = build_system(PSITestSystems, "modified_RTS_GMLC_DA_sys")`
The following components still exist (even though they're supposedly removed in line 3357 in PowerSystemCaseBuilder.jl/scr/system_library.jl. It looks like it's inside another loop where it shouldn't be.):
`    names = [
        "114_SYNC_COND_1",
        "314_SYNC_COND_1",
        "313_STORAGE_1",
        "214_SYNC_COND_1",
        "212_CSP_1",
    ]`

Test:
```
using PowerSystemCaseBuilder
using PowerSystems
const PSY = PowerSystems

sys = build_system(PSITestSystems, "modified_RTS_GMLC_DA_sys")
PSY.get_components(PSY.Generator, sys, x -> x.name == "114_SYNC_COND_1")
```

**Comment by jd-lara** [comment]
For the future records, this issue is related to https://github.com/NREL-SIIP/PowerSimulations.jl/issues/461 and the fact that the RTS models the sync gens as thermal units.
