### ISSUE TITLE
Switch over to Pluto?

### ISSUE THREAD

**Issue by jd-foster** [NREL-SIIP/SIIPExamples.jl#31]
Are there any arguments for or against changing over to Pluto rather than Jupyter?

I know that using JuMP code has trouble with Pluto due to macro handling (https://github.com/jump-dev/JuMP.jl/issues/2540)

**Comment by claytonpbarrows** [comment]
I tried this ~9 months ago, and encountered odd reactions similar to the ones described in the linked issue. If you want to try it, I'd be excited to entertain the idea if it works out.

**Comment by claytonpbarrows** [comment]
To my knowledge, this still is not really a viable pathway. I'll close for now. If it becomes viable, please reopen.
