### ISSUE TITLE
Typo: Operations

### ISSUE THREAD

**Issue by jd-lara** [NREL-SIIP/SIIPExamples.jl#45]
https://github.com/NREL-SIIP/SIIPExamples.jl/blob/182a54793b6189acafc5c1d21a4cc3856f9fa65a/script/3_PowerSimulations_examples/02_sequential_simulations.jl#L13

**Comment by claytonpbarrows** [comment]
cd7efe829cc45a99f83843ed7ad583ef34d6137b closes
