### ISSUE TITLE
UndefVarError: ExponentialLoad not defined

### ISSUE THREAD

**Issue by ychung66** [NREL-SIIP/SIIPExamples.jl#50]
I try to run the "02_line_dynamics.jl" in SIIPExamples.jl\script\4_PowerSimulationsDynamics_examples
see the following code in 02_line_dynamics.jl

# code block in 02_line_dynamics.jl
#Now, we construct the simulation:

#Time span of our simulation
tspan = (0.0, 30.0)

#Define Simulation
sim = PSD.Simulation(
    ResidualModel, #Type of model used
    threebus_sys, #system
    pwd(), #folder to output results
    tspan, #time span
    Ybus_change, #Type of perturbation
)

Error message
==================================
 Error: ResidualModel failed to build
│   exception =
│    UndefVarError: ExponentialLoad not defined
│    Stacktrace:
│      [1] (::PowerSimulationsDynamics.var"#11#12")(x::PowerLoad)
│        @ PowerSimulationsDynamics C:\julia_package\PowerSimulationsDynamics.jl\src\base\device_wrapper.jl:335
│      [2] filter(f::PowerSimulationsDynamics.var"#11#12", a::Vector{ElectricLoad})
│        @ Base .\array.jl:2484
│      [3] PowerSimulationsDynamics.StaticLoadWrapper(bus::Bus, loads::Vector{ElectricLoad}, bus_ix::Int64)
│        @ PowerSimulationsDynamics C:\julia_package\PowerSimulationsDynamics.jl\src\base\device_wrapper.jl:335
│      [4] _construct_load_wrapper(lookup::Dict{Int64, Int64}, map_bus_load::Dict{Bus, Vector{ElectricLoad}})
│        @ PowerSimulationsDynamics C:\julia_package\PowerSimulationsDynamics.jl\src\base\simulation_inputs.jl:253
│      [5] _wrap_loads(sys::System, lookup::Dict{Int64, Int64})
│        @ PowerSimulationsDynamics C:\julia_package\PowerSimulationsDynamics.jl\src\base\simulation_inputs.jl:242
│      [6] macro expansion
│        @ C:\julia_package\PowerSimulationsDynamics.jl\src\base\simulation_inputs.jl:47 [inlined]
│      [7] macro expansion
│        @ C:\Users\wayne\.julia\packages\TimerOutputs\nDhDw\src\TimerOutput.jl:236 [inlined]
│      [8] PowerSimulationsDynamics.SimulationInputs(sys::System, #unused#::Type{ReferenceBus})
│        @ PowerSimulationsDynamics C:\julia_package\PowerSimulationsDynamics.jl\src\base\simulation_inputs.jl:46
│      [9] PowerSimulationsDynamics.SimulationInputs(#unused#::Type{ResidualModel}, sys::System, frequency_reference::Type)
│        @ PowerSimulationsDynamics C:\julia_package\PowerSimulationsDynamics.jl\src\base\simulation_inputs.jl:137
│     [10] _build_inputs!(sim::Simulation{ResidualModel}, frequency_reference::Type)
...
│        @ IJulia C:\Users\wayne\.julia\packages\IJulia\AQu2H\src\eventloop.jl:8
│     [34] (::IJulia.var"#15#18")()
│        @ IJulia .\task.jl:423
└ @ PowerSimulationsDynamics C:\julia_package\PowerSimulationsDynamics.jl\src\base\simulation.jl:422

**Comment by jd-lara** [comment]
@ychung66 Can you confirm which version of PowerSystems and PowerSimulationsDynamics are you using? This is an off error since we haven't defined ExponentialLoad in a release yet.

**Comment by ychung66** [comment]
@jd-lara Yes, I have changed my software installation version and now everything is fine. Thanks !
